# Generated by Django 2.2.4 on 2019-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcode',
            name='user_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='NcDVErUlyM', max_length=10, unique=True),
        ),
    ]
