# Generated by Django 2.2.4 on 2019-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191005_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='nbbRvBUXjP', max_length=10, unique=True),
        ),
    ]
