# Generated by Django 2.2.4 on 2019-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191016_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='KDcMxKBXOA', max_length=10, unique=True),
        ),
    ]
