# Generated by Django 2.2.4 on 2019-10-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191016_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='ZJyIEawANr', max_length=10, unique=True),
        ),
    ]
