# Generated by Django 2.2.4 on 2019-10-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191021_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='xmlmtKLxGk', max_length=10, unique=True),
        ),
    ]
