# Generated by Django 2.2.4 on 2019-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191021_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='verify_code',
            field=models.CharField(default='ZjpigBXDGW', max_length=10, unique=True),
        ),
    ]
