# Generated by Django 2.2.4 on 2019-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageBuffer',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=4096)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.AddField(
            model_name='messagelogs',
            name='message',
            field=models.TextField(default='sample', max_length=4096),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
