# Generated by Django 2.2.4 on 2019-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_auto_20191016_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebuffer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagelogs',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagebuffer',
            name='id_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messagelogs',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
