# Generated by Django 2.2.4 on 2019-10-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_auto_20191016_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messageBuffer',
        ),
        migrations.DeleteModel(
            name='messageLogs',
        ),
    ]
